### ISSUE TITLE
[generate:entity:content] Don't generate entity autocomplete functionality

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalAppConsole#236]
This issue is a feature requirement.

The content entities generated's don't have the autocomplete functionality to be called by external forms

**Comment by vacho** [comment]
This issue has already been resolved by itself in the core. Currently the content entities that generates the console can be used to autocomplete in other forms.

**Comment by jmolivas** [comment]
Thanks for reporting and review this issue @vacho
