### ISSUE TITLE
Wrong brace position for generated classes and interfaces

### ISSUE THREAD

**Issue by bojanz** [hechoendrupal/DrupalAppConsole#258]
The generated code puts the opening brace on its own line, but according to https://www.drupal.org/node/608152 the brace needs to be  in the line where the class/interface is declared.

https://github.com/bojanz/workflow/commit/20fa62268861639e20038d5473b2351b6502452a

**Comment by jmolivas** [comment]
This will be fixed with PR #313

**Comment by jmolivas** [comment]
This is still happening

**Comment by jmolivas** [comment]
Since you send the PR #313 @danielnv18  may you test and confirm is fixed ?

**Comment by danielnv18** [comment]
@jmolivas yeap it's fixed

**Comment by jmolivas** [comment]
I test and it's fixed nice, thanks @danielnv18
