### ISSUE TITLE
Autoupdate console

### ISSUE THREAD

**Issue by danielnv18** [hechoendrupal/DrupalAppConsole#267]
Is there any change that the console can be autoupdated? Something similar to the way composer does it. 

I didn't see any command for autoupdate

**Comment by Chi-teck** [comment]
This article might be useful http://moquet.net/blog/distributing-php-cli/#auto-updates

**Comment by jmolivas** [comment]
Thanks @Chi-teck and @danielnv18, we are looking at this, feel free to send a PR :)

**Comment by dmouse** [comment]
This issue is solved in the PR #294, has been merged into the master branch

**Comment by danielnv18** [comment]
Just test for update the console.phar version from v0.6.3 to v0.6.4

**Comment by danielnv18** [comment]
Just a non-related comment
When I run `drupal self-update`, I feel like I'm updating drupal and not the drupal console

**Comment by jmolivas** [comment]
@danielnv18 running console as `drupal` is only an alias as you can see on [previous comment](https://github.com/hechoendrupal/DrupalAppConsole/issues/267#issuecomment-68222229)

you may try naming anything else, any name you want to 
```
$ mv console.phar /usr/local/bin/console
$ mv console.phar /usr/local/bin/drupal-console
$ mv console.phar /usr/local/bin/dconsole
$ mv console.phar /usr/local/bin/drupal-cli
$ mv console.phar /usr/local/bin/drucli
$ mv console.phar /usr/local/bin/drupcli
```
