### ISSUE TITLE
The Entity Generator creates files with spaces 

### ISSUE THREAD

**Issue by omero** [hechoendrupal/DrupalAppConsole#272]
When the entity generator ask for the name of the entity class and i write something like ``Product Entity`` the generator creates the files necessary for the entity with spaces and we have results like this:
![screen shot 2014-12-30 at 8 24 54 pm](https://cloud.githubusercontent.com/assets/1909779/5585243/3ecd996e-906b-11e4-96ca-aaef76a9ae83.png)

**Comment by jmolivas** [comment]
Fixed on latest release [v0.6.0](https://github.com/hechoendrupal/DrupalAppConsole/releases/tag/0.6.0)
