### ISSUE TITLE
PHP Fatal error:  Cannot redeclare React\Promise\resolve()

### ISSUE THREAD

**Issue by Chi-teck** [hechoendrupal/DrupalAppConsole#277]
I tried to run *bin/console* file with *drupal-8-beta-4* and got the following message:
> PHP Fatal error:  Cannot redeclare React\Promise\resolve() (previously declared in /var/www/DrupalAppConsole/vendor/react/promise/src/functions.php:5) in /var/www/drupal-8.0.0-beta4/core/vendor/react/promise/src/functions.php on line 12

 Is there something special to make it working without phar compilation?

**Comment by jmolivas** [comment]
I have not tested inside a Drupal installation since we have the installer & executable.

How do you installed and which version are you using @Chi-teck ?

**Comment by Chi-teck** [comment]
I am using last master branch. The generate commands work only inside Drupal installation. Right?
https://github.com/hechoendrupal/DrupalAppConsole/blob/master/bin/console.php#L54

**Comment by jmolivas** [comment]
Actually if you run the file outside a Drupal 8 root directory this should appear 

```
Drupal Console version 0.5.2 (prod)

Usage:
 [options] command [arguments]

Options:
 --help (-h)           Display this help message.
 --quiet (-q)          Do not output any message.
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.
 --version (-V)        Display this application version.
 --ansi                Force ANSI output.
 --no-ansi             Disable ANSI output.
 --no-interaction (-n) Do not ask any interactive question.
 --bootstrap-file (-b) Path to Drupal bootstrap file (core/includes/boostrap.inc).
 --shell (-s)          Launch the shell.
 --env (-e)            The Environment name. (default: "prod")
 --no-debug            Switches off debug mode.

Available commands:
 help   Displays help for a command
 list   Lists commands
```

**Comment by jmolivas** [comment]
Also @Chi-teck make sure you install using composer `--no-dev` before copy/move to Drupal 8 root directory
```
$ composer update --no-dev
```

**Comment by jmolivas** [comment]
May you run a tree command `tree vendor/ -L 2` and this should be the result.
```
vendor/
├── autoload.php
├── composer
│   ├── ClassLoader.php
│   ├── autoload_classmap.php
│   ├── autoload_namespaces.php
│   ├── autoload_psr4.php
│   ├── autoload_real.php
│   ├── installed.json
│   └── installers
├── symfony
│   ├── config
│   ├── console
│   ├── dependency-injection
│   ├── filesystem
│   ├── finder
│   ├── translation
│   └── yaml
└── twig
    └── twig
``` 
NOTE: You may not have `config`  and `translation` since those are part of the upcoming release

**Comment by Chi-teck** [comment]
> composer update --no-dev

It solved the problem. Thanks.
