### ISSUE TITLE
[generate:module] Don't generate module when path is wrong and wrong message

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalAppConsole#290]
I try generate a module with this params:
Enter the new module name: Client Register
Enter the module machine name [client_register]: 
Enter the module Path [/var/www/html/client-manager/modules/custom]: /var/www/html/client-manger/modules/client-manager
....

the folder "client-manger" don't exist and the module don't generate!! (good) but.... this message appear
 "You can now start using the generated code!"

**Comment by vacho** [comment]
I see that the code was generated. in the wrong path.. 
mmmmm 
may be we need validate if the path of code generated is in drupal instance.

**Comment by jmolivas** [comment]
make sense, may  ask for a relative path and prepend DRUPAL_ROOT
