### ISSUE TITLE
generate:form

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalAppConsole#292]
This issue is a feature requirement.

Vary very little to generate configurations form but is necessary for those who need a simple form.

**Comment by vacho** [comment]
This form maybe implements FormInterface directly.

**Comment by jmolivas** [comment]
May you share a link to the documentation ?

This sounds related to #171

**Comment by vacho** [comment]
exactly #jmolvias... this is an duplicated issue. 

sorry I don't see the #171  issue.
