### ISSUE TITLE
Text files should end with a newline character - in src/Utils/YamlFileDumper.php, line 85

### ISSUE THREAD

**Issue by danielnv18** [hechoendrupal/DrupalAppConsole#339]
**[in src/Utils/YamlFileDumper.php, line 85](https://github.com/danielnv18/DrupalAppConsole/blob/3860d6f259128b8e12c5778774f10bd2a6ef722d/src/Utils/YamlFileDumper.php#L85)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```php
   */
  protected function getExtension()
  {
    return 'yml';
  }
}
```

**Comment by jmolivas** [comment]
Thanks for taking care of this @danielnv18 :)
