### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by danielnv18** [hechoendrupal/DrupalAppConsole#341]
There are several variables that are declare but never user

**[in src/Command/GeneratorEntityCommand.php, line 64](https://github.com/hechoendrupal/DrupalAppConsole/blob/3860d6f259128b8e12c5778774f10bd2a6ef722d/src/Command/GeneratorEntityCommand.php#L64)**

> The `dialog` local variable is declared but never used.

**[in src/Command/GeneratorFormCommand.php, line 64](https://github.com/hechoendrupal/DrupalAppConsole/blob/3860d6f259128b8e12c5778774f10bd2a6ef722d/src/Command/GeneratorFormCommand.php#L64)**

> The `dialog` local variable is declared but never used.

**[in src/Command/MigrateExecuteCommand.php, line 201](https://github.com/hechoendrupal/DrupalAppConsole/blob/3860d6f259128b8e12c5778774f10bd2a6ef722d/src/Command/MigrateExecuteCommand.php#L201)**

> The `site_url` local variable is declared but never used.

**[in src/Command/MigrateExecuteCommand.php, line 252](https://github.com/hechoendrupal/DrupalAppConsole/blob/3860d6f259128b8e12c5778774f10bd2a6ef722d/src/Command/MigrateExecuteCommand.php#L252)**

> The `migration_name` local variable is declared but never used. 

These variables should be remove it.

**Comment by jmolivas** [comment]
Thanks this was a huge PR #342 thanks @danielnv18 :)
