### ISSUE TITLE
[helper] Improve validation for Class name

### ISSUE THREAD

**Issue by langelhc** [hechoendrupal/DrupalAppConsole#381]
I was creating a command and when I get promted:
     Enter the Command Class name [DefaultCommand]: qwer%w
I typed "%" and also typed an space for this value and I didn't get an error message.

This is the RegEx located in Validators.php:
     `REGEX_CLASS_NAME = '/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]+$/' `

I was reviewing this with https://www.regex101.com/
*\x7f-\xff a single character in the range between the following two characters
\x7f the character  with position 0x7f (127 decimal or 177 octal) in the character set
\xff the character ÿ with position 0xff (255 decimal or 377 octal) in the character set (case sensitive)*

**Comment by hugronaphor** [comment]
The RegEx by itself works as intended as recommended on http://php.net/manual/en/language.oop5.basic.php .
Validation was missing.
Created a PR:
https://github.com/hechoendrupal/DrupalAppConsole/pull/488

**Comment by hugronaphor** [comment]
Out of topic question:
What coding standards do we follow?

**Comment by jmolivas** [comment]
Since this project is not a Drupal module, the application code must follow:
* http://www.php-fig.org/psr/psr-1/
* http://www.php-fig.org/psr/psr-2/

Bu the generated result is a drupal module, that code must follow:
* https://www.drupal.org/coding-standards

**Comment by hugronaphor** [comment]
Jesus @jmolivas 
Make sense.

**Comment by jmolivas** [comment]
This is an issue related to what you just mentioned @hugronaphor 
* Clean up output code - https://github.com/hechoendrupal/DrupalAppConsole/issues/447

* Implement PSR2 coding standard for code-base - https://github.com/hechoendrupal/DrupalAppConsole/pull/400
