### ISSUE TITLE
[site:status] Add Site Status command

### ISSUE THREAD

**Issue by lucasmingarro** [hechoendrupal/DrupalAppConsole#410]
The idea is add a new command that provides a view of the current drupal installation. Is will be something like `drush st`

In this first approach the command should provide the following information.
#### Fields
- [x] Drupal Console version 
- [x] Drupal version
- Database 
  - [x] db driver
  - [x] db hostname
  - [x] db name
  - [x] db port
  - [x] db username
  - [x] db password
  - [ ] db status 
  - [x] db connection string url
- Theme
  - [x] Default theme
  - [x] Admin Theme
- Directories
  - [x] Drupal root directory
  - [ ] Site Path 
  - [x] Theme Path
  - [x] Temp file directory path
  - [ ] Config path
  
#### Output Format
- [x] std output
- [ ] cvs
- [x] json
- [ ] any other??

#### Defaults 
- [x] Drupal Console version 
- [x] Drupal version
- Database 
  - [x] db connection string url
- Theme
  - [ ] Default theme
- Directories
  - [x] Drupal root directory
- Output format
  - [x] std out

**Comment by jmolivas** [comment]
I like de idea of grouping them and the `db connection string url`

Related to output format `std output`, will be fine for the 1st iteration of the command class.

**Comment by jmolivas** [comment]
I believe a good name for this command could be `site:status` any thoughts on that @lucasmingarro

**Comment by lucasmingarro** [comment]
@jmolivas I think site:status is the better name thanks.

**Comment by jmolivas** [comment]
I make this command more simple and removed: 
* Output Format
* Defaults

The only missing values to display are:
* db status
* Site Path
* Config path

**Comment by jmolivas** [comment]
This is the `site:status` command output
![site-status](https://cloud.githubusercontent.com/assets/366275/6592270/d86b57f6-c788-11e4-8251-1da3458f12a1.png)

**Comment by jmolivas** [comment]
I am planning to close this issue since the PR was accepted and may add a new issue for the missing data mentioned above.

**Comment by jmolivas** [comment]
This was the final result: 

![console-learning-multilanguage](https://cloud.githubusercontent.com/assets/366275/6645148/512d6932-c977-11e4-9dee-4bf320b99b4b.gif)
