### ISSUE TITLE
[test] Test commands with the latest Drupal 8 beta7 release

### ISSUE THREAD

**Issue by jmolivas** [hechoendrupal/DrupalAppConsole#455]
Test commands with the latest Drupal 8 beta7 release 
https://www.drupal.org/node/2437851

* general
 - [x] `drush`
 - [x] `help`
 - [x] `list`
  - [ ] `self-update`
* cache
 - [x] `cache:rebuild`
* config
 - [x] `config:debug`
 - [x] `config:edit`
 - [x] `config:export`
 - [x] `config:override`
* container
 - [x] `container:debug`
* Generators
  - [x] `generate:authentication:provider`
  - [x] `generate:command`
  - [x] `generate:controller`
  - [x] `generate:entity:config`
  - [x] `generate:entity:content`
  - [ ] `generate:form:config`
  - [x] `generate:module`
  - [x] `generate:permissions`
  - [x] `generate:plugin:block`
  - [x] `generate:plugin:imageeffect`
  - [x] `generate:plugin:rest:resource`
  - [x] `generate:plugin:rulesaction`
  - [x] `generate:service`

* migrate
  - [x] `migrate:debug`
  - [x] `migrate:execute`
* module
  - [x] `module:debug`
  - [x] `module:download`
  - [x] `module:install`
  - [x] `module:uninstall`
* rest
  - [x] `rest:debug`
  - [x] `rest:disable`
  - [x] `rest:enable`
* router
  - [x] `router:debug`
  - [x] `router:rebuild`
* site
  - [x] `site:maintenance`
  - [x] `site:mode`
* test
  - [x] `test:debug`

**Comment by chipkaye** [comment]
Tested Console v0.7.2 against Drupal beta7 and found one error:

command "site:maintenance on" throws the following error from line 30 in file SiteMaintenanceCommand.php:

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "state.default".

It looks like "\Drupal\Core\State\StateInterface" is not defined as used in ContainerAwareCommand.php

**Comment by jmolivas** [comment]
I am testing the commands in order to have a release compatible with beta7

**Comment by jmolivas** [comment]
Issues:
#### Cache rebuild is not autocompleting caches [FIXED]

#### Site maintenance exception [FIXED]
```
$ site:maintenance on
$ site:maintenance off 
```
Are showing error:
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "state.default".
```

#### Generated form is not storing field form values
```
$ generate:form:config
```

####  Plugin Rest Resource generator [FIXED]
```
$ drupal generate:plugin:rest:resource
```
Error shown when enter to accept default value on: 
```
Enter the plugin rest resource name [DefaultRestResource]:
 The Class name can not be empty
```
#### Rule Action plugin generator
```
$ drupal generate:plugin:rulesaction
```
* Twig file not found [FIXED]
```
  [Twig_Error_Loader]
  Unable to find template "module/src/Plugin/RulesAction/rulesaction.php.twig" 
(looked into: phar:///usr/local/bin/drupal/src/Command/../../templates).
```
* Labels reference to block plugin and/or missing en value
```
Enter the module name: example
Plugin class name [DefaultBlock]:
Plugin label [default_block]:
Plugin id [default_block]:
commands.generate.plugin.block.options.category [default_block]:
commands.generate.plugin.block.options.context [default_block]:
Do you confirm generation [yes]?
```
