### ISSUE TITLE
generate:entity:content and hook_theme

### ISSUE THREAD

**Issue by grocc** [hechoendrupal/DrupalAppConsole#462]
Hi,
I need info about the generate:entity:content function. At the end of all it's giving me the message
$theme['subscriber'] = array(
  'render element' => 'elements',
  'file' => 'subscriber.page.inc',
  'template' => 'subscriber',
);
Where should i set this? 
Thanks!

**Comment by chipkaye** [comment]
Hi @grocc - after running generate:module, you should find a stub generated for hook_theme() in subscriber.module, like this:

/**
 * Implements hook_theme().
 */
function subscriber_theme() {
  $theme = [];

  return $theme;
}

You should add the content from generate:entity:content to this hook which would result in this:

/**
 * Implements hook_theme().
 */
function subscriber_theme() {
  $theme['subscriber'] = array(
    'render element' => 'elements',
    'file' => 'subscriber.page.inc',
    'template' => 'subscriber',
  );

  return $theme;
}

**Comment by grocc** [comment]
Wonderful! Thanks @chipkaye for the help!
