### ISSUE TITLE
[violation] Insight Test

### ISSUE THREAD

**Issue by danielnv18** [hechoendrupal/DrupalAppConsole#464]
[Insight] Files should not be executable
> Your project contains files with permissive permissions. In order to avoid opening a security breach, you should restrict execution rights on following files: 
- src/Generator/PluginRulesActionGenerator.php

```bash
chmod a-x 'src/Generator/PluginRulesActionGenerator.php'
```

---------------------

[Insight] Code should not be duplicated - in src/…/GeneratorPluginBlockCommand.php, line 70
**[in src/Command/GeneratorPluginBlockCommand.php, line 70](https://github.com/hechoendrupal/DrupalAppConsole/blob/d07bbdfe20ef4e6f998259ec000b9c04fbce8fce/src/Command/GeneratorPluginBlockCommand.php#L70)**

> The next 46 lines appear both in `src/Command/GeneratorPluginBlockCommand.php:70` and `src/Command/GeneratorPluginRulesActionCommand.php:66`.

```php
        $this
          ->getGenerator()
          ->generate($module, $class_name, $label, $plugin_id, $build_services, $inputs);
    }

    protected function interact(InputInterface $input, OutputInterface $output)
    {
        $dialog = $this->getDialogHelper();

        // --module option
        $module = $input->getOption('module');
```

**Comment by danielnv18** [comment]
@jmolivas I already fixed the first issue but I'm not sure how fix the last one

https://insight.sensiolabs.com/projects/cc529050-789e-45f1-8f1f-38aaa78f9307/analyses/25

**Comment by danielnv18** [comment]
Reviewing the code, both methods are exactly the same. Whats the difference from both generators?

**Comment by jmolivas** [comment]
We may implement something similar to entity generators: https://github.com/jmolivas/DrupalAppConsole/blob/master/src/Command/GeneratorEntityCommand.php

https://github.com/jmolivas/DrupalAppConsole/blob/master/src/Command/GeneratorEntityConfigCommand.php

https://github.com/jmolivas/DrupalAppConsole/blob/master/src/Command/GeneratorEntityContentCommand.php

**Comment by danielnv18** [comment]
mmm I get it. I thinks we should move / merge this code into a single function in a upper / different class.

honestly I don't know the app architect enough to move this code and remove the code violation

**Comment by jmolivas** [comment]
OK, I can take care, thanks for the PR and fixes
