### ISSUE TITLE
[console] Drupal compatibility testing

### ISSUE THREAD

**Issue by chipkaye** [hechoendrupal/DrupalAppConsole#481]
Issues #455 and #397 are pointing out the need for automated testing of Console in the context of a Drupal instance - i.e. "system" testing.  This seems like a critical need since Console - like Drush - is primarily a tool for manipulating the configuration and code of a Drupal instance. Current unit tests function mainly as a sanity check as run against the standalone Console code base.

Self-assigning this ticket and will look into how unit and system testing might be considered together looking forward.

**Comment by dmouse** [comment]
In #475 I am using a drupal installation and probe the commands into. 

I am create scripts to test behavior but we need more unit test for the code.

**Comment by chipkaye** [comment]
@dmouse already addressing system testing need in #475.
