### ISSUE TITLE
generate:entity:content file annotation is incorrect - module account?

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/DrupalAppConsole#533]
I love this project .... but using it I have found a bug.

I was using it to create a content entity type 

console generate:entity:content

with the following input 

module name: flag
entity class name: flagging
entity name flagging

everything works fine it creates a bundle of new files 

looking at the FlaggingAccessController.php file 

I see a tiny flaw, to report

/**
 * @file
 * Contains Drupal\account\FlaggingAccessController.
 */

the file annotation is wrong the project account is incorrect. it should be user defined ..in this case flag

This is just a bug report for the moment ... this weekend is busy, but next weekend I will have a look at tracking it down further...

**Comment by martinfrances107** [comment]
Structure of project was so cleanly laid out - the bug was easy to find and it  is a simple one line fix. :)

**Comment by jmolivas** [comment]
Thanks @martinfrances107 
You can send a PR from here:
https://github.com/hechoendrupal/DrupalAppConsole/compare/master...martinfrances107:master

**Comment by vacho** [comment]
I found that this issue could be easily solved .. hehehe ...
https://github.com/hechoendrupal/DrupalAppConsole/pull/544

**Comment by jmolivas** [comment]
This was already solved with https://github.com/hechoendrupal/DrupalAppConsole/pull/542

**Comment by jmolivas** [comment]
Thanks for sending the PR @vacho
