### ISSUE TITLE
[generate:entity:content] ingroup tag is incorrect

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/DrupalAppConsole#535]
This is a sister issue to 

https://github.com/hechoendrupal/DrupalAppConsole/issues/533

I am looking at the  entity interface template as used in the  generate:entity:content command

interface-entity-content.php.twig

The template contains a ingroup tag "account" when it should make use of  {{modfule}}

**Comment by martinfrances107** [comment]
/**
 * Provides an interface defining a {{ entity_class }} entity.
 * @ingroup account
 */

should read 

/**
 * Provides an interface defining a {{ entity_class }} entity.
 * @ingroup {{module}}
 */

**Comment by jmolivas** [comment]
Fee free to send a PR @martinfrances107 if you need any help creating the PR ping me

**Comment by martinfrances107** [comment]
This pull request should fix the issue 

https://github.com/hechoendrupal/DrupalAppConsole/pull/543
