### ISSUE TITLE
generate:entity:content produces inconsistent file annotation.

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/DrupalAppConsole#536]
So I can see this template file get the name of the class wrong in the file description block

accesscontrolhandler-entity-content.php.twig

the file_path block is 
Drupal\{{module}}\{{ entity_class }}AccessController.
and should read
Drupal\{{module}}\{{ entity_class }}AccessControlHandler.

that way the class name should be represented in the file description annotation.

**Comment by jmolivas** [comment]
Feel free to send a PR @martinfrances107

**Comment by jmolivas** [comment]
I will fix this
