### ISSUE TITLE
[generate:entity:content] checkCreateAccess template

### ISSUE THREAD

**Issue by martinfrances107** [hechoendrupal/DrupalAppConsole#539]
I found a bug in the accesscontrolhandler-entity-content.php.twig file

in the checkCreateAccess method 

    return AccessResult::allowedIfHasPermission($account, 'add Bar entity');

should read 

    return AccessResult::allowedIfHasPermission($account, 'add {{ entity_class }} entity');

**Comment by jmolivas** [comment]
Feel free to send a PR @martinfrances107

**Comment by martinfrances107** [comment]
This pull request should solve this issue

https://github.com/hechoendrupal/DrupalAppConsole/pull/540
